# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build_and_deploy:
    docker:
      # specify the version you desire here
      - image: circleci/node
    working_directory: ~/repo
    filters:
      branches:
        only: master
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: yarn && yarn lerna bootstrap
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      # run build!
      - run: yarn build

      # Deploy
      - add_ssh_keys:
          fingerprints:
            - "59:ad:fd:64:71:eb:81:01:6a:d7:1a:c9:0c:19:39:af"
      - run: touch packages/demo/dist/.nojekyll
      - run: git config user.email "ci@circleci.com" && git config user.name "CircleCI" && npx gh-pages --dotfiles -d packages/demo/dist

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build_and_deploy:
          filters:
            branches:
              only: master
