# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node

    working_directory: ~/repo

    steps:
      - checkout
      # run build!
      - run: npm ci && npm run build

  deploy:
    docker:
      - image: circleci/node
    working_directory: ~/repo
    steps:
      - checkout
      - run: cd example && npm ci && npm run build

      - add_ssh_keys:
          fingerprints:
            - "18:38:dd:2a:bb:ff:68:52:f7:32:3d:a6:a9:47:1c:62"

      - run:
          name: Install and configure dependencies
          command: |
            yarn global add gh-pages
            git config user.email "deploy@circleci.com"
            git config user.name "deploy"

      - run:
          name: Deploy docs to gh-pages branch
          command: |
            export PATH="$PATH:$HOME/.config/yarn/global/node_modules/.bin"
            gh-pages --dist example/dist

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build:
          filters:
            branches:
              only: master
      - deploy:
          filters:
            branches:
              only: master
